# Introduction to Python Matrices and NumPy #

Welcome to your first notebook of this specification! In this notebook, you will use NumPy to create 2-D arrays and easily compute mathematical operations. Numpy(Numerical Python) is an open-source package that is widely used in science and engineering. Feel free to skip this notebook if you are already fluent with NumPy.

### After this assignment you will be able to:
* Use Jupyter Notebook and its features.
* Use NumPy functions to create arrays and NumPy array operations.
* Use indexing and slicing for 2-D arrays.
* Find the shape of an array, reshape it and stack it horizontally and vertically.

### Instructions 
* You will be using Python3.
* Follow along the cells using `Shift` + `Enter`. Alternatively, you can press `Run` in the menu. 

## Table of Contents ## 
[About Jupyter Notebooks](#0)
- [1 - Basics of NumPy](#1)
   - [1.1 - Packages](#1-1)
   - [1.2 - Advantages of using NumPy arrays](#1-2)
   - [1.3 - How to create NumPy arrays](#1-3)
   - [1.4 - More on NumPy arrays](#1-4)
- [2 - Multidimensional arrays](#2)
   - [2.1 - Finding size, shape and dimension](#2-1)
- [3 - Array match operations](#3)
   - [3.1 - Multiplying vector with a scalar (broadcasting)](#3-1)
- [4 - Indexing and slicing](#4)
   - [4.1 - Indexing](#4-1)
   - [4.2 - Slicing](#4-2)
- [5 - Stacking](#5)
- [6 - Exercises](#6)

<a name='0'> </a>

## About Jupyter NoteBooks ## 
Jupyter Notebooks are interactive coding journals that integrate live code, explanatory text, equations,
visualizations and other multimedia resources, all in a single document. As a first exercise, run the test snippet below and the print statement cell for "Hello World".

In [2]:
# run the "hello world" in the cell below to print "hello world"
test = "hello world"

In [3]:
print(test)

hello world


<a name="1"></a>
# 1 - Basics of NumPy # 

Numpy is the main package for scientific computing in Python. It performs a wide variety of advanced mathematical operations with high efficiency. In this practice lab you will learn several key NumPy functions that will help you in future assignment, such as creating arrays, slicing, indexing, reshaping and stacking. 

<a name="1-1"></a>

## 1.1 - Packages ## 

Before you get started, you have to import NumPy  to load its functions. As you may notice, even though there is no expected output, when you run this cell, the Jupyter Notebook imports the package (often referred to as the library) and its functions. Try it for yourself and run the following cell. 

In [6]:
# pip3 install numpy 
import numpy as np 

<a name='1-2'></a>
## 1.2 - Advantages of using NumPy arrays ##

Arrays are one of the core data structures of the NumPy library, essential for organizing your data. You can think of them as a grid of values, all of the same type. If you have used Python lists before, you may remember that they are convenient, as you can store different data types. However, Python lists are limited in functions and take up more space and time to process than NumPy arrays. 

NumPy provides an array object that is much faster and more compact than Python lists. Through its extensive API integration, the library offers many built-in functions that make computing much easier with only a few lines of code. This can be a huge advantage when performing math operations on large datasets. 

The array object in NumPy is called `ndarray` meaning 'n-dimensional array'. To begin with, you will use one of the most common array types: the one-dimensional array ('1-D'). A 1-D array represents a standard list of values entirely in one dimension. Remember that in NumPy, all of the elements within the array are of the same type.

In [8]:
# here we create a one dimensioal array 
one_dimensinal_arr = np.array([10, 12])
print(type(one_dimensinal_arr))
print(one_dimensinal_arr)

<class 'numpy.ndarray'>
[10 12]


<a name='1-3'></a>
## 1.3 - How to create NumPy arrays ## 

There are several ways to create an array in NumPy. You can create a 1-D array by simply using the function `array()` which takes in a list of values as an argument and returns a 1-D array. 

In [9]:
# Create and print a NumPy array 'a' containing the elements 1,2,3
a = np.array([1,2,3])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3]


Another way to implement an array is using `np.arange()`. This function will return an array of evenly spaced values within a given interval. To learn more about the arguments that this functioin takes, there is a powerful feature in Jupyter Notebook that allows you to access the documentation of any function by simply pressing `shift+tab` on your keyboard when clicking on the function. Give it for the built-in documentation of `np.arange()`.

In [10]:
# Create array that starts form the integer 1, ends at 20, increased by 3. 
c = np.arange(1, 20, 3)
print(c)

[ 1  4  7 10 13 16 19]


What if you wanted to create an array with five evenly spaced values in the interval from 0 to 100? As you may notice, you have 3 parameters that a function must take. One parameter is the starting number, in this case 0, the final number 100 and the number of elements in the array, in this case, 5. 

Numpyhas a function that allows you to do specially this by using np.linspace().

In [11]:
lin_spaced_arr = np.linspace(0, 100, 5)
print(lin_spaced_arr)

[  0.  25.  50.  75. 100.]


Did you notice that the output of the function is presented in the float value form(e.g. "...25. 50. ...")? The reason is that the default type for values in the NumPy function `np.linspace` is a floating point (np.float64). You can easily specify your data type using `dtype`. If you access the built-in documentation of the function, you may notice that most functions take in an optional parameter `dtype`. In addition to float, NumPy has several other data types such as `int`, and `char`. 

To change the type to integers, you need to set the dtype to `int`. You can do so, even in the previous functions. Feel free to try it out and modify the cells to output your desired data type. 

In [15]:
lin_spaced_arr_int = np.linspace(0, 100, 100, dtype=int)
print(lin_spaced_arr_int)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98 100]


In [13]:
c_int = np.arange(1, 20, 3, dtype = int)
print(c_int)

[ 1  4  7 10 13 16 19]


In [14]:
b_float = np.arange(3, dtype=float)
print(b_float)

[0. 1. 2.]


In [16]:
# all object that are generated or wraped by NumPy#array supports call method .dtype 
char_arr = np.array(['Welcome to Math for ML!'])
print(char_arr)
print(char_arr.dtype) # prints the data type of the array 

['Welcome to Math for ML!']
<U23


Did you notice that the output of the data type of the `char_arr` array is `<U23`? This is means that the string (`Welcome to Math for ML!`) is a 23-character (23) unicode string (`U`) on a little-endian architecture(`<`). You can learn more about data types [here](https://numpy.org/doc/stable/user/basics.types.html). 

<a name='1-4'></a>
## 1.4 - More on NumPy arrays ## 

One of the advantages of using NumPy is that you can easily create arrays with built-in functions such as:

- `np.ones()` - Returns a new array setting values to one.
- `np.zeros()` - Returns a new array setting values to zero. 
- `np.empty()` - Returns a new uninitialized array.
- `np.random.rand()` - Returns a new array with values chosen at random.

In [17]:
# return a new array of shape 3, filled with ones 
ones_arr = np.ones(3)
print(type(ones_arr))
print(ones_arr)
print(len(ones_arr))

<class 'numpy.ndarray'>
[1. 1. 1.]
3


In [18]:
# return a new array of shape 3, filled with zeros. 
zeros_arr = np.zeros(3)
print(zeros_arr)
print(len(zeros_arr))
print(type(zeros_arr))

[0. 0. 0.]
3
<class 'numpy.ndarray'>


In [19]:
# Return a new array of shape 3, without initializing entries.
empt_arr = np.empty(3)
print(empt_arr)
print(type(empt_arr))
print(len(empt_arr))

[0. 0. 0.]
<class 'numpy.ndarray'>
3


In [20]:
# Return a new array of shape 3 with random numbers between 0 and 1. 
rand_arr = np.random.rand(3)
print(rand_arr)
print(len(rand_arr))
print(type(rand_arr))

[0.19460427 0.86384012 0.74092822]
3
<class 'numpy.ndarray'>


<a name='2'></a>
# 2 - Multidimensional Arrays #

With NumPy you can also create arrays with more than one dimension. In the above examples, you dealt with 1-D arrays, where you can access their elements using a single index. A multidimensional array has more than one column. Think of a multidimensional array as an excel sheet where each row/column represents a dimension. 

In [21]:
# create a 2 dimensional array (2-D)
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

[[1 2 3]
 [4 5 6]]


An alternative way to create a multidimensional arrray is by reshaping the initial 1-D array. Using `np.reshape()` you can rearrange elements of the previous array into a new shape. 

In [26]:
# first define a array of 1-D array
one_dim_arr = np.array([1,2,3,4,5,6,7,8])

# use reshape to convert 1-D 1 * 8 array into a 2 * 4 2-D array 
multi_dim_arr = np.reshape(one_dim_arr, (2,4))

print(multi_dim_arr)

# or what happen if we reshape into a 2 * 7 > total element count array ?
# it will print ValueError
#multi_dim_arr2 = np.reshape(one_dim_arr, (2, 7))
#print(multi_dim_arr2)

# or what happend if we reshape into a 2 * 2 < total element count 2-D array?
# also got a ValueError
# multi_dim_arr3 = np.reshape(one_dim_arr, (2,2))
#print(multi_dim_arr3)

# M * N of the reshape should equal to the element's total number 
# otherwise you will got an error of ValueError like
# the M * N == cnt(multi_dim_arr) otherwise it will got an exception of  ValueError: cannot reshape array of size 8 into shape (2,2)# 

[[1 2 3 4]
 [5 6 7 8]]


<a name='2-1'></a>
## 2.1 - Finding size, shape and dimension. ## 

In future assignments, you will need to know how to find the size, dimension and shape of an array. These are all attributes of a `ndarray` and canb e accessed as follows: 

- `ndarray.nidm` - Stores the number dimensions of the array.
- `ndarray.shape` - Stores the shape of the array. Each number in the tuple denotes the lengths of each corresponding dimension.


- `ndarray.size` - Stores the number of elements in the array. 

In [28]:
# get value of n-dimension of the multi-dimension(2-D) array: multi_dim_arr
print(multi_dim_arr.ndim) # 2-D should print 2 
print(type(multi_dim_arr.ndim)) # int type 

2
<class 'int'>


In [30]:
# get value of the shape of the n-dimension of the multi-dimension(2-D) array: multi_dim_arr
print(multi_dim_arr.shape) # should be 2 * 4
# here reshape it into a 4 * 2
reshape_arr = np.reshape(multi_dim_arr, (4,2))
print(reshape_arr)
print(multi_dim_arr.shape) # (2,4) the orignal shape value 
print(reshape_arr.shape)   # (4,2) the already shaped value 
print(type(reshape_arr.shape)) # type of the shape is a class of tuple 

(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(2, 4)
<class 'tuple'>
(4, 2)


In [32]:
# size of the array multi_dim_arr 
# returns total number of elements 
print(multi_dim_arr.size) # size is the total element, here return 8 
print(type(multi_dim_arr.size)) # int 

8
<class 'int'>


<a name='3'></a>
# 3 - Array math operations #
In this section, you will see that NumPy allows you to quickly perform elementwise addition, substraction, multiplication and division for both 1-D and multidimensional arrays. The operations are performed using the math symbol for each '+', '-' and '*'. Recall that addition of Python lists works completely differently as it would append the lists, thus making a longer list, in addition, subtraction and multiplicaiton of Python lists do not work.

In [35]:
arr_1 = np.array([2,4,6])
arr_2 = np.array([1,3,5])

# adding two 1-D arrays
addition = arr_1 + arr_2
print(addition)

# subtracting two 1-D arrays 
subtraction = arr_1 - arr_2 
print(subtraction)

# multiplying two 1-D arrays 
multiplication = arr_1 * arr_2 
print(multiplication)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


<a name='3-1'></a>

## 3.1 - Multiplying vector with a scalar (broadcasting) ## 
Suppose you need to convert miles to kilometers. To do so, you can use the NumPy array functions that you've learned so far. You can do this by carrying out an operation between an array(miles) and a single number (the conversion rate which is a scalar). Since, 1 mile = 1.6 km, NumPy computes each multiplicaiton within each cell. 

This concept is called **broadcasting**, which allows you to perform operations specifically on arrays of different shapes. 

In [39]:
vector = np.random.rand(4)
print(vector)
vector_multi_dim = np.reshape(vector, (2,2))
print(vector_multi_dim)
ans = vector_multi_dim * 100
print(ans)

[0.00857488 0.56246172 0.59306079 0.66291394]
[[0.00857488 0.56246172]
 [0.59306079 0.66291394]]
[[ 0.85748791 56.24617192]
 [59.30607901 66.29139382]]


<a name='4'></a>
# 4 - Indexing and slicing # 

Indexing is very useful as it allows you to select specific elements from an array. It also lets you select entire rows/columns or planes as you'll see in future assignments for multidimensional arrays. 

## 4.1 - Indexing ## 
Let us select specific elements from the arrays as given. 


In [42]:
# Select the third element of the array. Remember the counting starts from 0.
a = ([1,2,3,4,5,6])
print(a[2]) # a[0], a[1], a[2](3rd)

# Select the first element of the array.
print(a[0])

3
1


For multidimensional arrays of shape n, to index a specific element, you must input n indices, one for each dimension. 

In [43]:
# indexing a 2-D array 
two_dim = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(two_dim)

# select element number 8 from the 2-D array using indices i,j.
print(two_dim[2][1]) # which means the 3rd one in row/x-aix, the 2nd one in column/y-aix

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<a name='4-2'></a>
## 4.2 - Slicing ## 
Slicing gives you a sublist of elements that you specify from the array. The slice notation specifies a start and end value, and copies the list from start up to but not including the end (end-exclusive). 

The syntax is: 
`array[start:end:step]`

If no value is passed to start, it is assumed `start = 0`, if no value is passed to end, it is assumed that `end = length of array -1` and if no value is passed to step, it is assumed `step = 1`.

In [53]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)
# a = ([1,2,3,4,5,6])
arr = a[1:100:1]
print(arr)




[2, 3, 4]
[2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3]
[3, 4, 5]


In [55]:
# Slice the array to get the array [1,2,3]
print(a)
a1 = a[0:3:1]
print(a1)


[1, 2, 3, 4, 5, 6]
[1, 2, 3]


In [54]:
# Slice the array to get the array [3,4,5]
a1 = a[2:5]
print(a1)

[3, 4, 5]


In [56]:
# Slice the array to get the array [1,3,5]
a1 = a[::2]
print(a1)

[1, 3, 5]


In [57]:
# Note that a == a[:] = a[::]
print(a == a[:] == a[::])

True


In [58]:
# Slice the two_dim array to get the first two rows
sliced_arr = two_dim[0:2] # here the a:b a, b is refered to the rows 
print(sliced_arr)

[[1 2 3]
 [4 5 6]]


In [59]:
# Slice the two_dim array to get the last two rows 
sliced_arr = two_dim[1:3]
print(sliced_arr)

[[4 5 6]
 [7 8 9]]


In [60]:
# Slice the middle column of the 2-D array
sliced_arr = two_dim[:,1]
print(sliced_arr)

[2 5 8]


In [73]:
sliced_arr = two_dim[:,0:2] # select the [0,2) columns from the original 2-D array 
print(sliced_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<a name='5'></a>

# 5 - Stacking # 

Finally, stacking is a feature of NumPy that leads to increased customization of array. It means to join two or more arrays, either horizontally or vertically, meaning that it is done along a new axis. 

- `np.vstack()` - stacks vertically
- `np.hstack()` - stacks horizontally 
- `np.hsplit()` - splits an array into several smaller arrays

In [79]:
a1 = np.array([[1,1], [2,2]])  # 2 * 2 2-D array 
a2 = np.array([[3,3], [4,4]])
print(a1.ndim)
print(a1.shape)


print(a2.ndim)
print(a2.shape)


2
(2, 2)
2
(2, 2)


In [81]:
# Stack the arrays vertically 
vert_stack = np.vstack((a1, a2)) 

# vstack means vertically merge the two same dimensional and same shape arrays 
# vertically stack operation effects the stacked item's (array's) row value row = two stacked arrays sum up value 
print(vert_stack.ndim)
print(vert_stack.shape)

2
(4, 2)


In [82]:
# correspoindingly the hstack means the horizontal merge the two same dimensonal and same shape array together 
# horizontally stack operation effects the stacked result's column value column value = two stacked arrays' column value sum up value 


# actually, vertical stack requires the two stack merged array has the same column and modify the stacked result's row value 
# the horizontal stack requires the two stack merged array shares the same dimension and the same row and sum up the column value 


# Stack the arrays horizontally 
hori_stack = np.hstack((a1,a2))

# shape should be the 2 * 4 
print(hori_stack.ndim) # dimension value will not change 
print(hori_stack.shape)

2
(2, 4)
